version: 0.2

phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - npx install react-router-dom
      - echo ''
  build:
    commands:
      #test
      #build
      echo 'npm...'
      - npm run build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist